# Generated by Django 4.1.7 on 2023-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], max_length=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Restaurantes',
            new_name='Restaurante',
        ),
    ]
